name: CI-DEVELOPMENT

on:   
   pull_request:
      

jobs:

  build-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SHOW_SQL: true
          DB_DDL_AUTO: update
          DB_DIALECT: org.hibernate.dialect.MySQL8Dialect
          DB_FORMAT_SQL: true
          BATCH_JOB_ENABLED: true
        run: |
          mvn clean verify -Dmaven.test.skip=true \
            -Dspring.datasource.url=$DB_URL \
            -Dspring.datasource.username=$DB_USERNAME \
            -Dspring.datasource.password=$DB_PASSWORD \
            -Dspring.jpa.show-sql=true \
            -Dspring.jpa.hibernate.ddl-auto=$DB_DDL_AUTO \
            -Dspring.jpa.properties.hibernate.dialect=$DB_DIALECT \
            -Dspring.jpa.properties.hibernate.format_sql=true \
            -Dspring.batch.job.enabled=true

  build-push:
    runs-on: ubuntu-latest
    environment: dev
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USER }}/backend-app:${{ github.sha }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin


      - name: Push image
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/backend-app:${{ github.sha }}

  trigger-cd:
    runs-on: ubuntu-latest
    environment: dev
    needs: build-push
    steps:
      - name: Trigger CD
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/hakimsa/helm-releases/dispatches \
          -d '{"event_type":"deploy-dev","client_payload":{"image":"${{ github.sha }}"}}'