name: CI-DEVELOPMENT

on:
  push:
    branches:
        - develop   
  pull_request:
      branches:
        - develop
jobs:

  ci-wrapper:
    runs-on: ubuntu-latest
    environment: dev                  # 👈 job normal, puede declarar environment
    outputs:
      dockerhub-username: ${{ steps.vars.outputs.dockerhub-username }}
    steps:
      - name: Expose secrets as outputs
        id: vars
        run: echo "ready=true" >> $GITHUB_OUTPUT

  ci:
    needs: ci-wrapper
    uses: hakimsa/shared-workflows/.github/workflows/reusable-ci.yml@main
    with:
      docker-image-name: backend-mgt
      setup-java: true
      java-version: '17'
      install-command: mvn clean install -DskipTests
      build-command: mvn package -DskipTests
      lint-command: mvn checkstyle:check
      test-command: mvn test
      artifact-path: target/
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # heredado del entorno dev via needs
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}