name: CI - Java - Development

on:
  push:
    branches: [develop]
  
  # También ejecutar cuando se complete auto-merge
  workflow_run:
    workflows: ["Auto Merge PR"]
    types: [completed]
    branches: [develop]

jobs:
  ci:
    uses: hakimsa/shared-workflows/.github/workflows/reusable-ci.yml@main
    with:
      install-command: 'mvn clean install'
      build-command: 'mvn clean package'
      test-command: 'mvn test'
      lint-command: 'mvn checkstyle:check'
      setup-java: true
      docker-image-name: 'hakimsamouh/bakend-mgt'
      docker-registry: 'docker'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

#deploy to env development
  deploy-development:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    uses: hakimsa/shared-workflows/.github/workflows/reusable-cd.yml@main
    with:
      runner: self-hosted  
      environment: development
      deploy-tool: helm
      image-name: hakimsamouh/backend-mgt
      image-tag: ${{ github.sha }}
      helm-charts-repo: hakimsa/helm-releases   #  repo donde se encuentran los charts
      helm-charts-ref: develop  # branch
      helm-release-name: backend-app-develop
      helm-namespace: development
      helm-values-file: values.yaml        #  ruta dentro de helm-releases
      artifact-name: ${{ needs.ci.outputs.artifact-name }}
      
    secrets: 
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_STAGING }}  # secreto específico para staging
      CHARTS_TOKEN: ${{ secrets.GH_TOKEN }} 
      DB_URL: ${{ secrets.DB_URL }}                      
      DB_USER: ${{ secrets.DB_USER }}               
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}             
      SECURITY_PASSWORD: ${{ secrets.SECURITY_PASSWORD }}
    
