name: CI-PRODUCTION

on:
  push:
    tags:
      - 'v*'   # SOLO despliegue con tags
jobs:

  ci:
    uses: hakimsa/shared-workflows/.github/workflows/reusable-ci.yml@main
    with:
      docker-image-name: backend-mgt
      setup-java: true
      java-version: '17'
      install-command: mvn clean install -DskipTests
      build-command: mvn package -DskipTests
     # lint-command: mvn checkstyle:check    #Skipeando lint por ahora
      test-command: mvn test
      artifact-path: target/
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # heredado del entorno dev via needs
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}

#deploy to env production
  deploy-production:
    needs: ci
    if: startsWith(github.ref, 'refs/tags/v')
    uses: hakimsa/shared-workflows/.github/workflows/reusable-cd.yml@main
    with:
      runner: self-hosted  
      environment: production
      deploy-tool: helm
      image-name: hakimsamouh/backend-mgt
      image-tag: ${{ github.ref_name }}
      helm-charts-repo: hakimsa/helm-releases
      helm-charts-ref: main
      helm-release-name: backend-app-production
      helm-namespace: production
      helm-values-file: values.yaml
      artifact-name: ${{ needs.ci.outputs.artifact-name }}
    secrets: 
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_STAGING }}  # secreto específico para staging
      CHARTS_TOKEN: ${{ secrets.GH_TOKEN }}  

