name: CI-PREPRODUCTION

on:
  push:
    branches:
        - release/*  
  pull_request:
      branches:
        - release/*
jobs:


  ci:
    
    uses: hakimsa/shared-workflows/.github/workflows/reusable-ci.yml@main
    with:
      docker-image-name: backend-mgt
      setup-java: true
      java-version: '17'
      install-command: mvn clean install -DskipTests
      build-command: mvn package -DskipTests
     # lint-command: mvn checkstyle:check    #Skipeando lint por ahora
      test-command: mvn test
      artifact-path: target/
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # heredado del entorno dev via needs
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}

#deploy to env preproduction
  deploy-preproduction:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/realese'
    uses: hakimsa/shared-workflows/.github/workflows/reusable-cd.yml@main
    with:
      runner: self-hosted  
      environment: preproduction
      deploy-tool: helm
      image-name: hakimsamouh/backend-mgt
      image-tag: ${{ github.sha }}
      helm-charts-repo: hakimsa/helm-releases   #  repo donde se encuentran los charts
      helm-charts-ref: release/*               # branch
      helm-release-name: backend-app-preproduction
      helm-namespace: preproduction
      helm-values-file: values.yaml        #  ruta dentro de helm-releases
      artifact-name: ${{ needs.ci.outputs.artifact-name }}
      
    secrets: 
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_STAGING }}  # secreto específico para staging
      CHARTS_TOKEN: ${{ secrets.GH_TOKEN }}  

