name: CI-PREPRODUCTION

on:
  push:
    branches:
        - main 
  
jobs:


  ci:
    
    uses: hakimsa/shared-workflows/.github/workflows/reusable-ci.yml@main
    with:
      docker-image-name: backend-mgt
      setup-java: true
      environment: preproduction
      java-version: '17'
      install-command: mvn clean install -DskipTests
      build-command: mvn package -DskipTests
      artifact-path: target/
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # heredado del entorno dev via needs
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
       

  await-approval:
    needs: ci
    runs-on: ubuntu-latest
    environment: preproduction    # ← GitHub pausa aquí esperando aprobación QA
    steps:
      - name: Awaiting QA approval
        run: echo "CI passed — waiting for QA approval"    

#deploy to env preproduction
  deploy-preproduction:
    needs: [ci ,await-approval]

    if: ${{ success() }}
    uses: hakimsa/shared-workflows/.github/workflows/reusable-cd.yml@main
    with:
      runner: self-hosted  
      environment: preproduction-deploy
      deploy-tool: helm
      image-name: hakimsamouh/backend-mgt
      image-tag: ${{ github.sha }}
      helm-charts-repo: hakimsa/helm-releases   #  repo donde se encuentran los charts
      helm-charts-ref: main              # branch
      helm-release-name: backend-app-preproduction
      helm-namespace: preproduction
      helm-values-file: values.yaml        #  ruta dentro de helm-releases
      artifact-name: ${{ needs.ci.outputs.artifact-name }}
      
    secrets: 
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_STAGING }}  # secreto específico para staging
      CHARTS_TOKEN: ${{ secrets.GH_PAT }}
      DB_URL: ${{ secrets.DB_URL }}                      
      DB_USER: ${{ secrets.DB_USER }}               
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}             
      SECURITY_PASSWORD: ${{ secrets.SECURITY_PASSWORD }}