name: PR Validation

on:
  pull_request:
    branches:
      - develop
      - main
      
    types: [opened, synchronize, reopened]

jobs:
  validation:
    uses: hakimsa/shared-workflows/.github/workflows/reusable-ci.yml@main
    with:
      setup-java: true
      java-version: '17'
      environment: dev
      install-command: mvn clean install -DskipTests
      lint-command: mvn checkstyle:check
      test-command: mvn test
      build-command: mvn package -DskipTests
      artifact-path: target/
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  automerge:
    needs: validation
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Auto merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            })